<Project>

    <PropertyGroup>
        <RepositoryUrl>https://github.com/arcenox/TickerQ</RepositoryUrl>
        <PackageProjectUrl>https://tickerq.arcenox.com/</PackageProjectUrl>
        <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
        <PackageTags>ticker;queue;cron;time;scheduler;fire-and-forget</PackageTags>
        <PackageIcon>icon.jpg</PackageIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageVersion>1.0.10-local</PackageVersion>
		<PackageOutputPath>C:\Users\teru\source\repos\nuget</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\icon.jpg" Pack="true" PackagePath="\" />
    </ItemGroup>

    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

</Project>